pipeline { 
    agent{ 
       docker{ 
         image 'maven:3.9.8-sapmachine-21' 
         args '-v $HOME/.m2:/root/.m2' 
       } 
    } 
    stages{ 
        stage('build'){ 
            steps{ 
                echo 'building worker app' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            } 
        } 
        stage('test'){ 
            steps{ 
                echo 'running unit tests on worker app' 
                dir('worker'){ 
                  sh 'mvn clean test' 
                } 
            } 
        } 
        stage('package'){ 
            steps{ 
                echo 'packaging worker app into a jarfile'
                dir('worker'){ 
                  sh 'mvn package -DskipTests' 
                  archiveArtifacts artifacts: '**/target/*.jar', fingerprint:  true 
                } 
            } 
        } 
        stage('docker-package') {
          agent any
          steps {
            echo 'Packagin worker app with docker'
            script {
              docker.withRegistry('https://docker.io','yarel') {
                def workerImage = docker.build("yarel/worker:v${env.BUIILD_ID}","./worker")
                workerImage.push()
                workerImage.push("latest")
              }
            }
          }
        }
    }
    post{ 
        always{ 
            echo 'the job is complete' 
    }
  }
}


