pipeline { 
    agent any
    tools {
       maven 'maven  3.9.8'
    }

    stages{ 
        stage('build'){ 
            steps{ 
                echo 'compiling worker app..' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            } 
        } 
        stage('test'){ 
            steps{ 
                echo 'running unit tests on worker app' 
                dir('worker'){ 
                  sh 'mvn clean test' 
                } 
            } 
        } 
        stage('package'){ 
            steps{ 
                echo 'packaging worker app into a jarfile'
                dir('worker'){ 
                  sh 'mvn package -DskipTests' 
                } 
            } 
        } 
    }
    post{ 
        always{ 
            echo 'Building multibracnh pipeline for worker is completed..'

    }
  }
}
